### ISSUE TITLE
Error while loading DialogPlain.fnt asset bundle.

### ISSUE THREAD

**Issue by mwerle** [bfishman/Docking-Port-Alignment-Indicator#5]
Error while loading the dialog asset. Doesn't appear to affect the running of the mod itself, but should get investigated and cleaned up.

> Error while downloading Asset Bundle: Failed to decompress data for the AssetBundle 'file:///S:\KSP\KSP_Dev\GameData\NavyFish\Plugins\Docking Port Alignment Indicator\PluginData\DockingPortAlignmentIndicator\DialogPlain.fnt'.
> FontLoader: Bundle is null
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogError(Object)
> <LoadBundle>d__20:MoveNext()
> UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at C:\buildslave\unity\build\Runtime\Export\Scripting\Coroutines.cs:17)

**Comment by 7ranceaddic7** [comment]
nudge.

**Comment by MOARdV** [comment]
FWIW, I believe the problem is Unity is trying to load that font file as a specific format and failing because of the file extension.

A year ago, I had a 'bootleg' version of DPAI that I was working on that moved DialogPlain.fnt into an asset bundle so that Unity would stop trying and failing to load it.  I think that's what you'd need to do to get rid of this error.  I don't think I still have that code locally, since I cleaned out a lot of the side projects I was working on last year.

**Comment by mwerle** [comment]
> FWIW, I believe the problem is Unity is trying to load that font file as a specific format and failing because of the file extension.

Yeah, I had come to the same conclusion, but then forgot about trying it out before making the next release.  I was simply going to rename the file to ".dat" or something (it doesn't really matter as the plugin loads it manually)

Thanks for the hint re asset bundle, I'll try it out.

**Comment by mwerle** [comment]
So just renaming the file was sufficient.
